### ISSUE TITLE
$bumpmap potentially should have green value inverted

### ISSUE THREAD

**Issue by Igrium** [syborg64/BlenderVertexLitGeneric#1]
Source engine natively uses DirectX normal maps, while Blender uses OpenGL normal maps. While converting between the two is not difficult (just invert the green channel), it IS something worth taking into account.

The `$bumpmap` input in the `VertexLitGeneric` node group plugs directly into the diffuse shader, which is NOT accurate to how Source engine handles normal maps. Given that Blender artists are used to OpenGL normal maps, whether or not this should be fixed internally  is up for debate. It is worth thinking about however.

**Comment by syborg64** [comment]
That's a valid question to ponder. I don't believe any solution is fundamentally better than the other.
My choice was motivated for the following reasons:

- blender itself being OpenGL, people who have the expertise would expect it to use the OpenGL standard
- outside of game file rips, most content seems to use OpenGL as well
- with the intergration with SourceIO (which does the normalmap conversion when importing VTFs), it makes a lot more sense to have the inversion happen only once
- direct use with baking and/or the bump2normal utility node which I use a lot
- additionally, this tool was designed primarily for creation and export, and as such throwing the texture files into gimp for combining was already required and meant it was straightforward to do the inversion at that point

In order to better accommodate the source engine workflow, I have included an InvertG node and placed it in front of the $bumpmap input in the default material, in hopes of people finding it useful.

I considered placing the inverter inside the shader node  to allow the effect to be global, but personally did not find it to be useful

Unless a better solution presents itself, I consider this problem solved
